# Generated by Django 4.1.4 on 2023-01-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Robot',
        ),
    ]
